### ISSUE TITLE
negative scale values

### ISSUE THREAD

**Issue by cytosin12** [tobjaw/distillation-automation#66]

**Comment by tobjaw** [comment]
Did some debugging 🔎  

The scale code currently works by reading 6 Bytes, checking the parity Byte to see if the scale word is valid, and then converting that word to a float.  
Turns out the parity can be valid even if the word is garbage. 
E.g. `word[6] = {'0', '\0', '\0', '0', '0', '\0'};` does not make any sense, but still matches the parity code. 
We'll have to implement additional checks to improve the reliability of the scale protocol:  
1. Check if `word[0]` - `word[3]` are ASCII encoded numbers
2. Check if `word[6] == '\0'`
3. (Check parity, already implemented)
